### ISSUE TITLE
Delete old zips without flash

### ISSUE THREAD

**Issue by davepwsmith** [omnirom/android_packages_apps_OpenDelta#20]
I only tend to apply the open delta once a week. I don't know about you, but flashing a zip with three commits to the Samsung tree on my nexus 4 seems a bit pointless. This means that gigabytes of zips pile up in my open delta folder. Is there any reason  that the zips in between the last known working zip and the latest update can't be deleted by open delta?

**Comment by sedrubal** [comment]
:+1:

**Comment by maxwen** [comment]
They are deleted - only the last zip is kept

**Comment by sedrubal** [comment]
Mh that's the content of `/sdcard/OpenDelta`

```
$ ls -l
total 3411396
drwxrwx---    2 root     sdcard_r      4096 Nov 15 14:27 FlashAfterUpdate
-rw-rw----    1 root     sdcard_r 388135277 Nov 16 08:06 omni-5.1.1-20151116-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135303 Nov 19 08:21 omni-5.1.1-20151119-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135291 Nov 20 07:08 omni-5.1.1-20151120-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135320 Nov 21 09:44 omni-5.1.1-20151121-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135340 Nov 22 06:20 omni-5.1.1-20151122-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135321 Nov 23 06:59 omni-5.1.1-20151123-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135323 Nov 25 03:49 omni-5.1.1-20151125-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135295 Nov 30 08:34 omni-5.1.1-20151130-hammerhead-NIGHTLY.zip
-rw-rw----    1 root     sdcard_r 388135349 Dec  2 12:09 omni-5.1.1-20151202-hammerhead-NIGHTLY.zip
```

**Comment by maxwen** [comment]
Do you actually flash those or just download them :)
Cause if you dont intent to flash an image you should also not download it
See also https://github.com/omnirom/android_packages_apps_OpenDelta/blob/android-5.1/src/eu/chainfire/opendelta/UpdateService.java#L2082
They are not deleted for a reason in that case.

**Comment by sedrubal** [comment]
No I actually flash every day ;)

**Comment by maxwen** [comment]
Then create me a logcat please.  Of a full download and flash cycle (before rebooting ofc)

**Comment by sedrubal** [comment]
I don't know if this is a useful logcat, as I don't know much about android logging, etc...

**while downloading:**

```logcat
V/WindowManager(  730): Adding window Window{17c3ab3f u0 com.fsck.k9/com.fsck.k9.activity.setup.FolderSettings} at 14 of 21 (after Window{1f4a5186 u0 AtchDlg:com.fsck.k9/com.fsck.k9.activity.FolderList EXITING})E/WifiStateMachine(  730): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=04:bd:88:6a:a7:50 RSSI=-72D/ConnectivityManager.CallbackHandler( 1032): CM callback handler got msg 524290E/WifiStateMachine(  730): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=04:bd:88:6a:a7:50 RSSI=-76D/ConnectivityManager.CallbackHandler( 1032): CM callback handler got msg 524290D/OpenDelta( 8488): battery state --> 1
--
D/OpenDelta( 8488): screen state --> 0
D/OpenDelta( 8488): isScreenStateEnabled = true
I/OpenDelta( 8488): Setting sleep detection alarm (exact) for 21:27
--
D/OpenDelta( 8488): screen state --> 1
D/OpenDelta( 8488): isScreenStateEnabled = false
D/OpenDelta( 8488): Cancelling sleep detection alarmD/Vpn     (  730): setting state=CONNECTING, reason=establish
--
D/OpenDelta( 8488): onReceive state = action_build
D/OpenDelta( 8488): autoState state = action_build userInitiated = true checkOnly = 1
D/OpenDelta( 8488): Checking step done
D/OpenDelta( 8488): Update available
--
D/OpenDelta( 8488): onReceive state = action_buildW/ResourceType( 1032): No package identifier when getting value for resource number 0x00000000
D/OpenDelta( 8488): checkForUpdates checkOnly = 3 updateRunning = false userInitiated = true networkState.getState() = true batteryState.getState() = true screenState.getState() = true
I/OpenDelta( 8488): Starting check for updates
D/WifiService(  730): acquireWifiLockLocked: WifiLock{OpenDelta WifiLock type=1 binder=android.os.BinderProxy@20da79db}
D/OpenDelta( 8488): onSharedPreferenceChanged latest_full_name
D/OpenDelta( 8488): Checking for latest full build
D/OpenDelta( 8488): download: https://dl.omnirom.org/json.php
D/OpenDelta( 8488): onSharedPreferenceChanged latest_delta_name
D/OpenDelta( 8488): onSharedPreferenceChanged download_size
D/OpenDelta( 8488): latest full build for device hammerhead is https://dl.omnirom.org/hammerhead/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151203-hammerhead-NIGHTLY.delta
D/OpenDelta( 8488): onSharedPreferenceChanged latest_full_name
D/OpenDelta( 8488): delta --> [omni-5.1.1-20151204-hammerhead-NIGHTLY.zip]
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151204-hammerhead-NIGHTLY.delta
D/OpenDelta( 8488): response: 404
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151204-hammerhead-NIGHTLY.delta_revoked
D/OpenDelta( 8488): response: 404
D/OpenDelta( 8488): download size --> deltas[958952] vs full[224181952]
D/OpenDelta( 8488): initial: /storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.zip
D/OpenDelta( 8488): onSharedPreferenceChanged latest_delta_name
D/OpenDelta( 8488): check donne: latest valid delta update = omni-5.1.1-20151204-hammerhead-NIGHTLY.zip : latest full build available = omni-5.1.1-20151204-hammerhead-NIGHTLY.zip : updateAvilable = true : downloadFullBuild = false
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151203-hammerhead-NIGHTLY.update --> /storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.update
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151203-hammerhead-NIGHTLY.update
D/OpenDelta( 8488): onSharedPreferenceChanged download_size
D/OpenDelta( 8488): success
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151203-hammerhead-NIGHTLY.sign --> /storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.sign
D/OpenDelta( 8488): download: https://delta.omnirom.org/nightlies/hammerhead/omni-5.1.1-20151203-hammerhead-NIGHTLY.sign
D/OpenDelta( 8488): success
D/OpenDelta( 8488): zipadjust [/storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.zip] --> [/storage/emulated/0/OpenDelta/temp1]
D/OpenDelta( 8488): zipadjust --> 1
D/OpenDelta( 8488): dedelta [/storage/emulated/0/OpenDelta/temp1] --> [/storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.update] --> [/storage/emulated/0/OpenDelta/temp2]
--
E/native  (  730): do suspend trueD/OpenDelta( 8488): screen state --> 0
D/OpenDelta( 8488): isScreenStateEnabled = true
I/OpenDelta( 8488): Setting sleep detection alarm (exact) for 21:30
--
D/ChimeraCfgMgr( 1883): Loading module com.google.android.gms.cast from APK com.google.android.gmsE/WifiStateMachine(  730): WifiStateMachine L2Connected CMD_START_SCAN source -2 776, 777 -> obsoleteD/OpenDelta( 8488): dedelta --> 1
D/OpenDelta( 8488): dedelta [/storage/emulated/0/OpenDelta/temp2] --> [/storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.sign] --> [/storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip]D/BluetoothAdapter( 1032): 139240260: getState() :  mService = null. Returning STATE_OFF
--
D/OpenDelta( 8488): dedelta --> 1
D/OpenDelta( 8488): final verification complete
D/OpenDelta( 8488): onSharedPreferenceChanged initial_file
D/OpenDelta( 8488): onSharedPreferenceChanged delta_signature
D/OpenDelta( 8488): onSharedPreferenceChanged ready_filename
D/OpenDelta( 8488): onSharedPreferenceChanged last_check_time
D/WifiService(  730): releaseWifiLockLocked: WifiLock{OpenDelta WifiLock type=1 binder=android.os.BinderProxy@20da79db}
D/OpenDelta( 8488): autoState state = action_applying_md5 userInitiated = true checkOnly = 3
D/OpenDelta( 8488): Update found: /storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zipI/PowerManagerService(  730): Waking up from dozing (uid 1000)...
--
D/OpenDelta( 8488): screen state --> 1
D/OpenDelta( 8488): isScreenStateEnabled = false
D/OpenDelta( 8488): Cancelling sleep detection alarmD/Vpn     (  730): setting state=CONNECTING, reason=establish
--
D/OpenDelta( 8488): onReceive state = action_ready
D/OpenDelta( 8488): autoState state = action_ready userInitiated = true checkOnly = 1
D/OpenDelta( 8488): Update found: /storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip
D/OpenDelta( 8488): onReceive state = action_ready
```

**before flashing:**

```logcat
D/WifiService(  730): acquireWifiLockLocked: WifiLock{OpenDelta WifiLock type=1 binder=android.os.BinderProxy@20da79db}
D/OpenDelta( 8488): dedelta --> 1
D/OpenDelta( 8488): dedelta [/storage/emulated/0/OpenDelta/temp2] --> [/storage/emulated/0/OpenDelta/omni-5.1.1-20151203-hammerhead-NIGHTLY.sign] --> [/storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip]
D/OpenDelta( 8488): dedelta --> 1
D/OpenDelta( 8488): final verification complete
D/OpenDelta( 8488): onSharedPreferenceChanged initial_file
D/OpenDelta( 8488): onSharedPreferenceChanged delta_signature
D/OpenDelta( 8488): onSharedPreferenceChanged ready_filename
D/OpenDelta( 8488): onSharedPreferenceChanged last_check_time
D/WifiService(  730): releaseWifiLockLocked: WifiLock{OpenDelta WifiLock type=1 binder=android.os.BinderProxy@20da79db}
D/OpenDelta( 8488): autoState state = action_applying_md5 userInitiated = true checkOnly = 3
D/OpenDelta( 8488): Update found: /storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip
D/OpenDelta( 8488): screen state --> 1
D/OpenDelta( 8488): isScreenStateEnabled = false
D/OpenDelta( 8488): Cancelling sleep detection alarm
D/OpenDelta( 8488): onReceive state = action_ready
D/OpenDelta( 8488): autoState state = action_ready userInitiated = true checkOnly = 1
D/OpenDelta( 8488): Update found: /storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip
D/OpenDelta( 8488): onReceive state = action_ready
D/OpenDelta( 8488): screen state --> 0
D/OpenDelta( 8488): isScreenStateEnabled = true
I/OpenDelta( 8488): Setting sleep detection alarm (exact) for 21:31
D/OpenDelta( 8488): screen state --> 1
D/OpenDelta( 8488): isScreenStateEnabled = false
D/OpenDelta( 8488): Cancelling sleep detection alarm
D/OpenDelta( 8488): onReceive state = action_ready
D/OpenDelta( 8488): autoState state = action_ready userInitiated = true checkOnly = 1
D/OpenDelta( 8488): Update found: /storage/emulated/0/OpenDelta/omni-5.1.1-20151204-hammerhead-NIGHTLY.zip
D/OpenDelta( 8488): onReceive state = action_ready
D/OpenDelta( 8488): flashUpdate
D/OpenDelta( 8488): onSharedPreferenceChanged latest_full_name
D/OpenDelta( 8488): onSharedPreferenceChanged latest_delta_name
D/OpenDelta( 8488): onSharedPreferenceChanged ready_filename
D/OpenDelta( 8488): onSharedPreferenceChanged download_size
D/OpenDelta( 8488): onSharedPreferenceChanged delta_signature
D/OpenDelta( 8488): onSharedPreferenceChanged initial_file
D/OpenDelta( 8488): flashUpdate - delete initial file
D/OpenDelta( 8488): flashUpdate - extra files to flash []
D/OpenDelta( 8488): flashUpdate - create /cache/recovery/keys
D/OpenDelta( 8488): flashUpdate - create /cache/recovery/openrecoveryscript
D/OpenDelta( 8488): flashUpdate - reboot to recovery
```

**Comment by maxwen** [comment]
Well 
> D/OpenDelta( 8488): flashUpdate - delete initial file
If the file is still there after that (initial file is 20151204) then something is wrong

**Comment by sedrubal** [comment]
Yes, it is still here...

**Comment by maxwen** [comment]
Not much more possible then calling file delete actually

**Comment by maxwen** [comment]
https://github.com/omnirom/android_packages_apps_OpenDelta/blob/android-5.1/src/eu/chainfire/opendelta/UpdateService.java#L1474

**Comment by sedrubal** [comment]
I don't know anything about Android programming, but don't you have to check if deletion was successful?

https://docs.oracle.com/javase/6/docs/api/java/io/File.html#delete%28%29

**Comment by maxwen** [comment]
LOL - I can - but WTH you think I should do if it wasnt? :)

**Comment by sedrubal** [comment]
you could log "Deletion was unsuccessful"

**Comment by maxwen** [comment]
useless information

**Comment by maxwen** [comment]
Wha wrong button :P

**Comment by maxwen** [comment]
Well - I will leave this just here until someone finds a fix for it :)

**Comment by sedrubal** [comment]
ok thx ;)

**Comment by maxwen** [comment]
this should fix it https://gerrit.omnirom.org/16348

**Comment by sedrubal** [comment]
Oh great :-1: do you know until when this patch is available in omnirom?

**Comment by maxwen** [comment]
when 6.0 nightlies get rolling

**Comment by sedrubal** [comment]
Mh meanwhile I updated omnirom 6.0.1 some times but this issue persists...

**Comment by maxwen** [comment]
Just in case that you have not noticed
the change has not even been merged

**Comment by sedrubal** [comment]
Want to report that this is still not working :D

**Comment by maxwen** [comment]
In the meantime you should know what to do.

**Comment by sedrubal** [comment]
Nope, sorry

**Comment by maxwen** [comment]
whenever you see one - delete it ☺

**Comment by sedrubal** [comment]
So wontfix?
